user  nginx;
worker_processes  auto;
error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    # 用户端 :80
    server {
        listen       80;
        server_name  _;
        root   /usr/share/nginx/html/user;
        index  index.html;

        location /user/     { proxy_pass http://192.168.100.128:8080; }
        location /products/ { proxy_pass http://192.168.100.128:8080; }
        location /cart/     { proxy_pass http://192.168.100.128:8080; }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }

    # 管理端 :81
    server {
        listen       81;
        server_name  _;
        root   /usr/share/nginx/html/admin;
        index  index.html;

        location /admin/    { proxy_pass http://192.168.100.128:8080; }
        location /products/ { proxy_pass http://192.168.100.128:8080; }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
