apiVersion: apps/v1
kind: Deployment
metadata:
  name: coupon-service
  namespace: bysj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coupon-service
  template:
    metadata:
      labels:
        app: coupon-service
    spec:
      nodeName: zabbix-monitor
      containers:
      - name: coupon-service
        image: bysj-coupon-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8086
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: bysj-config
              key: MYSQL_HOST
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: bysj-config
              key: MYSQL_PORT
        - name: MYSQL_DB
          valueFrom:
            configMapKeyRef:
              name: bysj-config
              key: MYSQL_DB
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://$(MYSQL_HOST):$(MYSQL_PORT)/$(MYSQL_DB)?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: bysj-config
              key: MYSQL_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: bysj-config
              key: MYSQL_PASSWORD
        - name: JAVA_OPTS
          value: "-Xms64m -Xmx128m -XX:+UseSerialGC"
        - name: SPRING_REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: bysj-config
              key: REDIS_HOST
        - name: SPRING_REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: bysj-config
              key: REDIS_PORT
        - name: SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR
          valueFrom:
            configMapKeyRef:
              name: bysj-config
              key: NACOS_ADDR
        - name: SPRING_CLOUD_NACOS_DISCOVERY_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
