apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailadmin
  namespace: bysj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailadmin
  template:
    metadata:
      labels:
        app: mailadmin
    spec:
      nodeName: zabbix-monitor
      containers:
      - name: mailadmin
        image: bysj-mailadmin:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: bysj-config
              key: MYSQL_HOST
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: bysj-config
              key: MYSQL_PORT
        - name: MYSQL_DB
          valueFrom:
            configMapKeyRef:
              name: bysj-config
              key: MYSQL_DB
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://$(MYSQL_HOST):$(MYSQL_PORT)/$(MYSQL_DB)?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: bysj-config
              key: MYSQL_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: bysj-config
              key: MYSQL_PASSWORD
        - name: JAVA_OPTS
          value: "-Xms128m -Xmx256m -XX:+UseSerialGC"
        - name: SPRING_RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: bysj-config
              key: RABBITMQ_HOST
        - name: SPRING_RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: bysj-config
              key: RABBITMQ_PORT
        - name: SPRING_RABBITMQ_USERNAME
          valueFrom:
            configMapKeyRef:
              name: bysj-config
              key: RABBITMQ_USER
        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: bysj-config
              key: RABBITMQ_PASS
        - name: MINIO_URL
          valueFrom:
            configMapKeyRef:
              name: bysj-config
              key: MINIO_URL
        - name: MINIO_ACCESS_NAME
          valueFrom:
            configMapKeyRef:
              name: bysj-config
              key: MINIO_ACCESS
        - name: MINIO_ACCESS_SECRET
          valueFrom:
            configMapKeyRef:
              name: bysj-config
              key: MINIO_SECRET
        - name: MINIO_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: bysj-config
              key: MINIO_BUCKET
        - name: SPRING_REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: bysj-config
              key: REDIS_HOST
        - name: SPRING_REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: bysj-config
              key: REDIS_PORT
        - name: SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR
          valueFrom:
            configMapKeyRef:
              name: bysj-config
              key: NACOS_ADDR
        - name: SPRING_CLOUD_NACOS_DISCOVERY_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
