user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log notice;
pid /var/run/nginx.pid;
events { worker_connections 1024; }
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;
    upstream gateway_cluster {
        server 192.168.100.128:30080;
        server 192.168.100.129:30080;
        server 192.168.100.130:30080;
    }
    server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html/user;
        index index.html;
        location /user/     { proxy_pass http://gateway_cluster; proxy_set_header Host $host; }
        location /products/ { proxy_pass http://gateway_cluster; proxy_set_header Host $host; }
        location /cart/     { proxy_pass http://gateway_cluster; proxy_set_header Host $host; }
        location /coupons/  { proxy_pass http://gateway_cluster; proxy_set_header Host $host; }
        location /refunds/  { proxy_pass http://gateway_cluster; proxy_set_header Host $host; }
        location /reviews/  { proxy_pass http://gateway_cluster; proxy_set_header Host $host; }
        location / { try_files $uri $uri/ /index.html; }
    }
    server {
        listen 81;
        server_name _;
        root /usr/share/nginx/html/admin;
        index index.html;
        location /admin/    { proxy_pass http://gateway_cluster; proxy_set_header Host $host; }
        location /products/ { proxy_pass http://gateway_cluster; proxy_set_header Host $host; }
        location /coupons/  { proxy_pass http://gateway_cluster; proxy_set_header Host $host; }
        location /refunds/  { proxy_pass http://gateway_cluster; proxy_set_header Host $host; }
        location /reviews/  { proxy_pass http://gateway_cluster; proxy_set_header Host $host; }
        location / { try_files $uri $uri/ /index.html; }
    }
}
